name: Run Tests with Allure Report

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Allure CLI
        uses: simple-elf/allure-report-action@v1.9
        with:
          allure-results: target/allure-results
          allure-report: allure-report
          allure-version: 2.24.1


      - name: Build and run tests
        run: mvn clean test

#      - name: Generate Allure Report
#        run: allure generate target/allure-results --clean -o allure-report

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
